services:
  - type: web
    name: rms-multitech
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PORT
        value: 10000
